server:
  port: 10000

spring:
  datasource:
    name: MySQL
    url: jdbc:mysql://192.168.199.86:3306/hantest?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: ddb_dev
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    maxActive: 1000
    minIdle: 5
    maxWait: 10000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    logSlowSql: true

swagger:
    host: 127.0.0.1:9000
    enable: true
logging:
    config: classpath:logs.xml
    level:
         com.jinglitong.shop.mapper: debug	


level.member: hehuoren
level.date: 2099-06-20 23:59:59